/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-01 06:34:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bubble_005fchart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bubble_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/highcharts-more.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("<script src=\"https://code.highcharts.com/modules/accessibility.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<figure class=\"highcharts-figure\">\r\n");
      out.write("  <div id=\"container\"></div>\r\n");
      out.write("  <p class=\"highcharts-description\">\r\n");
      out.write("    This chart shows how packed bubble charts can be grouped by series,\r\n");
      out.write("    creating a hierarchy.\r\n");
      out.write("  </p>\r\n");
      out.write("</figure>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write(" Highcharts.chart('container', {\r\n");
      out.write("  chart: {\r\n");
      out.write("    type: 'packedbubble',\r\n");
      out.write("    height: '100%'\r\n");
      out.write("  },\r\n");
      out.write("  title: {\r\n");
      out.write("    text: 'Carbon emissions around the world (2014)'\r\n");
      out.write("  },\r\n");
      out.write("  tooltip: {\r\n");
      out.write("    useHTML: true,\r\n");
      out.write("    pointFormat: '<b>{point.name}:</b> {point.value}m CO<sub>2</sub>'\r\n");
      out.write("  },\r\n");
      out.write("  plotOptions: {\r\n");
      out.write("    packedbubble: {\r\n");
      out.write("      minSize: '20%',\r\n");
      out.write("      maxSize: '100%',\r\n");
      out.write("      zMin: 0,\r\n");
      out.write("      zMax: 1000,\r\n");
      out.write("      layoutAlgorithm: {\r\n");
      out.write("        gravitationalConstant: 0.05,\r\n");
      out.write("        splitSeries: true,\r\n");
      out.write("        seriesInteraction: false,\r\n");
      out.write("        dragBetweenSeries: true,\r\n");
      out.write("        parentNodeLimit: true\r\n");
      out.write("      },\r\n");
      out.write("      dataLabels: {\r\n");
      out.write("        enabled: true,\r\n");
      out.write("        format: '{point.name}',\r\n");
      out.write("        filter: {\r\n");
      out.write("          property: 'y',\r\n");
      out.write("          operator: '>',\r\n");
      out.write("          value: 150\r\n");
      out.write("        },\r\n");
      out.write("        style: {\r\n");
      out.write("          color: 'black',\r\n");
      out.write("          textOutline: 'none',\r\n");
      out.write("          fontWeight: 'normal'\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  },\r\n");
      out.write("  series: [{\r\n");
      out.write("    name: 'Europe',\r\n");
      out.write("    data: [{\r\n");
      out.write("      name: 'Germany',\r\n");
      out.write("      value: 767.1\r\n");
      out.write("    }, {\r\n");
      out.write("      name: 'Croatia',\r\n");
      out.write("      value: 20.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Belgium\",\r\n");
      out.write("      value: 97.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Czech Republic\",\r\n");
      out.write("      value: 111.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Netherlands\",\r\n");
      out.write("      value: 158.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Spain\",\r\n");
      out.write("      value: 241.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Ukraine\",\r\n");
      out.write("      value: 249.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Poland\",\r\n");
      out.write("      value: 298.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"France\",\r\n");
      out.write("      value: 323.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Romania\",\r\n");
      out.write("      value: 78.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"United Kingdom\",\r\n");
      out.write("      value: 415.4\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Turkey\",\r\n");
      out.write("      value: 353.2\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Italy\",\r\n");
      out.write("      value: 337.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Greece\",\r\n");
      out.write("      value: 71.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Austria\",\r\n");
      out.write("      value: 69.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Belarus\",\r\n");
      out.write("      value: 67.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Serbia\",\r\n");
      out.write("      value: 59.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Finland\",\r\n");
      out.write("      value: 54.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Bulgaria\",\r\n");
      out.write("      value: 51.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Portugal\",\r\n");
      out.write("      value: 48.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Norway\",\r\n");
      out.write("      value: 44.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Sweden\",\r\n");
      out.write("      value: 44.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Hungary\",\r\n");
      out.write("      value: 43.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Switzerland\",\r\n");
      out.write("      value: 40.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Denmark\",\r\n");
      out.write("      value: 40\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Slovakia\",\r\n");
      out.write("      value: 34.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Ireland\",\r\n");
      out.write("      value: 34.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Croatia\",\r\n");
      out.write("      value: 20.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Estonia\",\r\n");
      out.write("      value: 19.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Slovenia\",\r\n");
      out.write("      value: 16.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Lithuania\",\r\n");
      out.write("      value: 12.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Luxembourg\",\r\n");
      out.write("      value: 10.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Macedonia\",\r\n");
      out.write("      value: 9.5\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Moldova\",\r\n");
      out.write("      value: 7.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Latvia\",\r\n");
      out.write("      value: 7.5\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Cyprus\",\r\n");
      out.write("      value: 7.2\r\n");
      out.write("    }]\r\n");
      out.write("  }, {\r\n");
      out.write("    name: 'Africa',\r\n");
      out.write("    data: [{\r\n");
      out.write("      name: \"Senegal\",\r\n");
      out.write("      value: 8.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Cameroon\",\r\n");
      out.write("      value: 9.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Zimbabwe\",\r\n");
      out.write("      value: 13.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Ghana\",\r\n");
      out.write("      value: 14.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Kenya\",\r\n");
      out.write("      value: 14.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Sudan\",\r\n");
      out.write("      value: 17.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Tunisia\",\r\n");
      out.write("      value: 24.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Angola\",\r\n");
      out.write("      value: 25\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Libya\",\r\n");
      out.write("      value: 50.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Ivory Coast\",\r\n");
      out.write("      value: 7.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Morocco\",\r\n");
      out.write("      value: 60.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Ethiopia\",\r\n");
      out.write("      value: 8.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"United Republic of Tanzania\",\r\n");
      out.write("      value: 9.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Nigeria\",\r\n");
      out.write("      value: 93.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"South Africa\",\r\n");
      out.write("      value: 392.7\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Egypt\",\r\n");
      out.write("      value: 225.1\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Algeria\",\r\n");
      out.write("      value: 141.5\r\n");
      out.write("    }]\r\n");
      out.write("  }, {\r\n");
      out.write("    name: 'Oceania',\r\n");
      out.write("    data: [{\r\n");
      out.write("      name: \"Australia\",\r\n");
      out.write("      value: 409.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"New Zealand\",\r\n");
      out.write("      value: 34.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Papua New Guinea\",\r\n");
      out.write("      value: 7.1\r\n");
      out.write("    }]\r\n");
      out.write("  }, {\r\n");
      out.write("    name: 'North America',\r\n");
      out.write("    data: [{\r\n");
      out.write("      name: \"Costa Rica\",\r\n");
      out.write("      value: 7.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Honduras\",\r\n");
      out.write("      value: 8.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Jamaica\",\r\n");
      out.write("      value: 8.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Panama\",\r\n");
      out.write("      value: 10.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Guatemala\",\r\n");
      out.write("      value: 12\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Dominican Republic\",\r\n");
      out.write("      value: 23.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Cuba\",\r\n");
      out.write("      value: 30.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"USA\",\r\n");
      out.write("      value: 5334.5\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Canada\",\r\n");
      out.write("      value: 566\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Mexico\",\r\n");
      out.write("      value: 456.3\r\n");
      out.write("    }]\r\n");
      out.write("  }, {\r\n");
      out.write("    name: 'South America',\r\n");
      out.write("    data: [{\r\n");
      out.write("      name: \"El Salvador\",\r\n");
      out.write("      value: 7.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Uruguay\",\r\n");
      out.write("      value: 8.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Bolivia\",\r\n");
      out.write("      value: 17.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Trinidad and Tobago\",\r\n");
      out.write("      value: 34\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Ecuador\",\r\n");
      out.write("      value: 43\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Chile\",\r\n");
      out.write("      value: 78.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Peru\",\r\n");
      out.write("      value: 52\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Colombia\",\r\n");
      out.write("      value: 74.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Brazil\",\r\n");
      out.write("      value: 501.1\r\n");
      out.write("    }, {\r\n");
      out.write("      name: \"Argentina\",\r\n");
      out.write("      value: 199\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Venezuela\",\r\n");
      out.write("      value: 195.2\r\n");
      out.write("    }]\r\n");
      out.write("  }, {\r\n");
      out.write("    name: 'Asia',\r\n");
      out.write("    data: [{\r\n");
      out.write("      name: \"Nepal\",\r\n");
      out.write("      value: 6.5\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Georgia\",\r\n");
      out.write("      value: 6.5\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Brunei Darussalam\",\r\n");
      out.write("      value: 7.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Kyrgyzstan\",\r\n");
      out.write("      value: 7.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Afghanistan\",\r\n");
      out.write("      value: 7.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Myanmar\",\r\n");
      out.write("      value: 9.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Mongolia\",\r\n");
      out.write("      value: 14.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Sri Lanka\",\r\n");
      out.write("      value: 16.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Bahrain\",\r\n");
      out.write("      value: 20.5\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Yemen\",\r\n");
      out.write("      value: 22.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Jordan\",\r\n");
      out.write("      value: 22.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Lebanon\",\r\n");
      out.write("      value: 21.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Azerbaijan\",\r\n");
      out.write("      value: 31.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Singapore\",\r\n");
      out.write("      value: 47.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Hong Kong\",\r\n");
      out.write("      value: 49.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Syria\",\r\n");
      out.write("      value: 52.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"DPR Korea\",\r\n");
      out.write("      value: 59.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Israel\",\r\n");
      out.write("      value: 64.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Turkmenistan\",\r\n");
      out.write("      value: 70.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Oman\",\r\n");
      out.write("      value: 74.3\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Qatar\",\r\n");
      out.write("      value: 88.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Philippines\",\r\n");
      out.write("      value: 96.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Kuwait\",\r\n");
      out.write("      value: 98.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Uzbekistan\",\r\n");
      out.write("      value: 122.6\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Iraq\",\r\n");
      out.write("      value: 139.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Pakistan\",\r\n");
      out.write("      value: 158.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Vietnam\",\r\n");
      out.write("      value: 190.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"United Arab Emirates\",\r\n");
      out.write("      value: 201.1\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Malaysia\",\r\n");
      out.write("      value: 227.5\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Kazakhstan\",\r\n");
      out.write("      value: 236.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Thailand\",\r\n");
      out.write("      value: 272\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Taiwan\",\r\n");
      out.write("      value: 276.7\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Indonesia\",\r\n");
      out.write("      value: 453\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Saudi Arabia\",\r\n");
      out.write("      value: 494.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Japan\",\r\n");
      out.write("      value: 1278.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"China\",\r\n");
      out.write("      value: 10540.8\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"India\",\r\n");
      out.write("      value: 2341.9\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Russia\",\r\n");
      out.write("      value: 1766.4\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Iran\",\r\n");
      out.write("      value: 618.2\r\n");
      out.write("    },\r\n");
      out.write("    {\r\n");
      out.write("      name: \"Korea\",\r\n");
      out.write("      value: 610.1\r\n");
      out.write("    }]\r\n");
      out.write("  }]\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
