/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-08 04:05:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bubble_005fchart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bubble_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1666585443141L));
    _jspx_dependants.put("jar:file:/C:/Users/thddy/OneDrive/바탕%20화면/프로젝트/final_project/빅데이터%20시각화%20프로젝트/infographic/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/chart_practice/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/Users/thddy/OneDrive/바탕%20화면/프로젝트/final_project/빅데이터%20시각화%20프로젝트/infographic/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/chart_practice/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<script src=\"https://code.highcharts.com/highcharts.js\"></script>\r\n");
      out.write("	<script src=\"https://code.highcharts.com/highcharts-more.js\"></script>\r\n");
      out.write("	<script src=\"https://code.highcharts.com/modules/exporting.js\"></script>\r\n");
      out.write("	<script src=\"https://code.highcharts.com/modules/accessibility.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("	\r\n");
      out.write("	");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<figure class=\"highcharts-figure\">\r\n");
      out.write("		<div id=\"container\"></div>\r\n");
      out.write("	</figure>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("		let value = new Array();\r\n");
      out.write("		let size = new Array();\r\n");
      out.write("		\r\n");
      out.write("		 window.onload = function() {\r\n");
      out.write("			let obj = \"\";\r\n");
      out.write("			let xhr = new XMLHttpRequest();\r\n");
      out.write("			xhr.open(\"GET\", \"/bubble_chart/bubble1.ch \", true);\r\n");
      out.write("			xhr.send();\r\n");
      out.write("			xhr.onreadystatechange = function() {\r\n");
      out.write("				if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200) {\r\n");
      out.write("					obj = JSON.parse(xhr.responseText);\r\n");
      out.write("					// alert(obj)\r\n");
      out.write("					for (let i = 0; i < obj.search_word2.length; i++) {\r\n");
      out.write("						value[i] = obj.search_word2[i].comments;\r\n");
      out.write("						// alert(value[i])\r\n");
      out.write("						\r\n");
      out.write("// 		 	let obj2 = \"\";\r\n");
      out.write("// 			let xhr2 = new XMLHttpRequest();\r\n");
      out.write("// 			xhr2.open(\"GET\", \"data3.json\", true);\r\n");
      out.write("// 			xhr2.send();\r\n");
      out.write("// 			xhr2.onreadystatechange = function() {\r\n");
      out.write("// 				if (xhr2.readyState == XMLHttpRequest.DONE && xhr2.status == 200) {\r\n");
      out.write("// 					obj2 = JSON.parse(xhr2.responseText);\r\n");
      out.write("// 					for (let i = 0; i < obj2.search_word.length; i++) {\r\n");
      out.write("// 						size[i] = obj2.search_word[i].size;    \r\n");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("		// <chart부분>				\r\n");
      out.write("		var chart = Highcharts.chart('container', {\r\n");
      out.write("		  chart: {\r\n");
      out.write("		    type: 'packedbubble',\r\n");
      out.write("		    height: '50%'\r\n");
      out.write("		  },\r\n");
      out.write("		  title: {\r\n");
      out.write("		    text: 'Comments by age'\r\n");
      out.write("		  },\r\n");
      out.write("		  tooltip: {\r\n");
      out.write("		    useHTML: true,\r\n");
      out.write("		    pointFormat: '<b>{point.name}:</b> {point.value}명'\r\n");
      out.write("		  },\r\n");
      out.write("		  plotOptions: {\r\n");
      out.write("		    packedbubble: {\r\n");
      out.write("		      minSize: '10%',\r\n");
      out.write("		      maxSize: '50%',\r\n");
      out.write("		      zMin: 0,\r\n");
      out.write("		      zMax: 1000,\r\n");
      out.write("		      layoutAlgorithm: {\r\n");
      out.write("		        gravitationalConstant: 0.05,\r\n");
      out.write("		        splitSeries: true,\r\n");
      out.write("		        seriesInteraction: false,\r\n");
      out.write("		        dragBetweenSeries: true,\r\n");
      out.write("		        parentNodeLimit: true\r\n");
      out.write("		      },\r\n");
      out.write("		      dataLabels: {\r\n");
      out.write("		        enabled: true,\r\n");
      out.write("		        format: '{point.name}',\r\n");
      out.write("		        filter: {\r\n");
      out.write("		          property: 'y',\r\n");
      out.write("		          operator: '>',\r\n");
      out.write("		          value: 150\r\n");
      out.write("		        },\r\n");
      out.write("		        style: {\r\n");
      out.write("		          color: 'black',\r\n");
      out.write("		          textOutline: 'none',\r\n");
      out.write("		          fontWeight: 'normal'\r\n");
      out.write("		        }\r\n");
      out.write("		      }\r\n");
      out.write("		    }\r\n");
      out.write("		  },\r\n");
      out.write("		  series: [ {\r\n");
      out.write("		    name: '10대',\r\n");
      out.write("		    data: [ {\r\n");
      out.write("		      name: value[0],\r\n");
      out.write("		      value: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("		    },\r\n");
      out.write("		    {\r\n");
      out.write("		        name: value[1],\r\n");
      out.write("		        value: size[1]\r\n");
      out.write("		      },\r\n");
      out.write("		    {\r\n");
      out.write("		        name: value[2],\r\n");
      out.write("		        value: size[2]\r\n");
      out.write("		      },\r\n");
      out.write("		    {\r\n");
      out.write("		        name: value[3],\r\n");
      out.write("		        value: size[3]\r\n");
      out.write("		      },\r\n");
      out.write("		      {\r\n");
      out.write("		          name: value[4],\r\n");
      out.write("		          value: size[4]\r\n");
      out.write("		        }\r\n");
      out.write("		    ]\r\n");
      out.write("		  \r\n");
      out.write("		  }, {\r\n");
      out.write("			  name: '20대',\r\n");
      out.write("			    data: [ {\r\n");
      out.write("			      name: value[0],\r\n");
      out.write("			      value: size[0]\r\n");
      out.write("			    },\r\n");
      out.write("			    {\r\n");
      out.write("			        name: value[1],\r\n");
      out.write("			        value: size[1]\r\n");
      out.write("			      },\r\n");
      out.write("			    {\r\n");
      out.write("			        name: value[2],\r\n");
      out.write("			        value: size[2]\r\n");
      out.write("			      },\r\n");
      out.write("			    {\r\n");
      out.write("			        name: value[3],\r\n");
      out.write("			        value: size[3]\r\n");
      out.write("			      },\r\n");
      out.write("			      {\r\n");
      out.write("			          name: value[4],\r\n");
      out.write("			          value: size[4]\r\n");
      out.write("			        }\r\n");
      out.write("			    ]\r\n");
      out.write("		  \r\n");
      out.write("		  \r\n");
      out.write("		  }]\r\n");
      out.write("		  \r\n");
      out.write("		});\r\n");
      out.write("					}}}}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /bubble_chart/bubble.jsp(18,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cnt");
      // /bubble_chart/bubble.jsp(18,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.cnt }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
